# Generated by Django 3.2.7 on 2021-09-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default='cashier', max_length=20),
        ),
    ]
